pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                echo "Cloned repository from GitHub"
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('task_1') {
                    bat 'docker build -t hello-devops:latest .'
                }
            }
        }

        stage('Run Container') {
            steps {
                dir('task_1') {
                    bat 'docker run --rm hello-devops:latest'
                }
            }
        }
    }

    post {
        always {
            echo 'Pipeline finished'
        }
    }
}
