pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                echo 'Cloning repository from GitHub'
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('task_1') {
                    bat 'docker build -t hello-devops:latest .'
                }
            }
        }

        stage('Run and Test Container') {
            steps {
                dir('task_1') {
                    bat '''
                        echo Starting container...
                        docker run -d --name hello-test -p 5000:5000 hello-devops:latest

                        echo Waiting for app to start...
                        timeout /t 5 >nul

                        echo Checking if app is running...
                        docker ps

                        echo Fetching container logs:
                        docker logs hello-test

                        echo Stopping container...
                        docker stop hello-test
                        docker rm hello-test
                    '''
                }
            }
        }
    }

    post {
        always {
            echo 'Pipeline execution complete. Cleaning up resources...'
            bat 'docker system prune -f'
        }
        success {
            echo '✅ Build & Test completed successfully!'
        }
        failure {
            echo '❌ Build failed. Check logs above for details.'
        }
    }
}
